build_trace <- function(){
  trace <- data.frame(matrix(ncol = 84))
  colnames(trace) <- c('Cycle',
                       'Time (Weeks)',
                       'Time (Months)',
                       'Time (Years)',
                       'Discounting (Costs)',
                       'Discounting (Benefits)',				
                       'PFS',
                       'OS',
                       'PFS (cohort)',
                       'OS (cohort)',
                       'Dead (new)',
                       'Dead (ACM)',
                       'Dead (total)',
                       'AE1',
                       'AE2',	
                       'AE3',	
                       'AE4',	
                       'AE5',
                       'AE6',	
                       'AE7',	
                       'AE8',	
                       'AE9',
                       'AE10',
                       'PFS cost (undiscounted)',
                       'PD cost (undiscounted)',
                       'Death cost (undiscounted)',
                       'Treatment cost (undiscounted)',
                       'AE1 cost (undiscounted)',
                       'AE2 cost (undiscounted)',	
                       'AE3 cost (undiscounted)',	
                       'AE4 cost (undiscounted)',	
                       'AE5 cost (undiscounted)',
                       'AE6 cost (undiscounted)',	
                       'AE7 cost (undiscounted)',	
                       'AE8 cost (undiscounted)',	
                       'AE9 cost (undiscounted)',
                       'AE10 cost (undiscounted)',
                       'Total AE cost (undiscounted)',
                       'PFS cost (discounted)',
                       'PD cost (discounted)',
                       'Death cost (discounted)',
                       'Treatment cost (discounted)',
                       'AE1 cost (discounted)',
                       'AE2 cost (discounted)',	
                       'AE3 cost (discounted)',	
                       'AE4 cost (discounted)',	
                       'AE5 cost (discounted)',
                       'AE6 cost (discounted)',	
                       'AE7 cost (discounted)',	
                       'AE8 cost (discounted)',	
                       'AE9 cost (discounted)',
                       'AE10 cost (discounted)',
                       'Total AE cost (discounted)',
                       'PFS utility (undiscounted)',
                       'PD utility (undiscounted)',
                       'Age utility (undiscounted)',
                       'AE1 utility (undiscounted)',
                       'AE2 utility (undiscounted)',
                       'AE3 utility (undiscounted)',
                       'AE4 utility (undiscounted)',
                       'AE5 utility (undiscounted)',
                       'AE6 utility (undiscounted)',
                       'AE7 utility (undiscounted)',
                       'AE8 utility (undiscounted)',
                       'AE9 utility (undiscounted)',
                       'AE10 utility (undiscounted)',
                       'Total AE utility (undiscounted)',
                       'PFS utility (discounted)',
                       'PD utility (discounted)',
                       'Age utility (discounted)',
                       'AE1 utility (discounted)',
                       'AE2 utility (discounted)',
                       'AE3 utility (discounted)',
                       'AE4 utility (discounted)',
                       'AE5 utility (discounted)',
                       'AE6 utility (discounted)',
                       'AE7 utility (discounted)',
                       'AE8 utility (discounted)',
                       'AE9 utility (discounted)',
                       'AE10 utility (discounted)',
                       'Total AE utility (discounted)',
                       'Life years',
                       'Total QALY (undiscounted)',
                       'Total QALY (discounted)')
}
